name: System Tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches: [master]
  workflow_dispatch: {}
  schedule:
    - cron:  '00 04 * * 2-6'

jobs:
  system-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - weblog-variant: express4
          - weblog-variant: express4-typescript
    env:
      TEST_LIBRARY: nodejs
      DD_API_KEY: ${{ secrets.DD_API_KEY }}

    steps:
      - name: Checkout system tests
        uses: actions/checkout@v2
        with:
          repository: 'DataDog/system-tests'

      - name: Checkout dd-trace-js
        uses: actions/checkout@v2
        with:
          path: 'binaries/dd-trace-js'

      - name: Build
        run: ./build.sh

      - name: Run
        run: ./run.sh

      - name: Compress artifact
        if: ${{ always() }}
        run: tar -czvf artifact.tar.gz $(ls | grep logs)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs_express-poc
          path: artifact.tar.gz

  parametric:
    runs-on: ubuntu-latest
    env:
      CLIENTS_ENABLED: nodejs
      NODEJS_DDTRACE_MODULE: datadog/dd-trace-js#${{ github.sha }}
      OVERRIDE_SKIPS: test_headers_b3_extract_valid,test_headers_b3_extract_invalid,test_headers_b3_inject_valid,test_headers_b3multi_propagate_valid,test_headers_b3multi_propagate_invalid,test_headers_b3multi_extract_valid,test_headers_b3multi_extract_invalid,test_headers_b3multi_inject_valid,test_headers_b3multi_propagate_valid,test_headers_b3multi_propagate_invalid,test_headers_datadog_extract_valid,test_headers_datadog_extract_invalid,test_headers_datadog_inject_valid,test_headers_datadog_propagate_valid,test_headers_datadog_propagate_invalid,test_headers_none_extract,test_headers_none_extract_with_other_propagators,test_headers_none_inject,test_headers_none_inject_with_other_propagators,test_headers_none_propagate,test_headers_precedence_propagationstyle_default,test_headers_precedence_propagationstyle_tracecontext,test_headers_precedence_propagationstyle_datadog,test_headers_precedence_propagationstyle_datadog_tracecontext,test_both_traceparent_and_tracestate_missing,test_traceparent_included_tracestate_missing,test_traceparent_duplicated,test_traceparent_header_name,test_traceparent_header_name_valid_casing,test_traceparent_version_0x00,test_traceparent_version_0xcc,test_traceparent_version_0xff,test_traceparent_version_illegal_characters,test_traceparent_version_too_long,test_traceparent_version_too_short,test_traceparent_trace_id_all_zero,test_traceparent_trace_id_illegal_characters,test_traceparent_trace_id_too_long,test_traceparent_trace_id_too_short,test_traceparent_parent_id_all_zero,test_traceparent_parent_id_illegal_characters,test_traceparent_parent_id_too_long,test_traceparent_parent_id_too_short,test_traceparent_trace_flags_illegal_characters,test_traceparent_trace_flags_too_long,test_traceparent_trace_flags_too_short,test_traceparent_ows_handling,test_tracestate_included_traceparent_missing,test_tracestate_included_traceparent_included,test_tracestate_header_name,test_tracestate_header_name_valid_casing,test_tracestate_empty_header,test_tracestate_multiple_headers_different_keys,test_tracestate_duplicated_keys,test_tracestate_all_allowed_characters,test_tracestate_ows_handling,test_headers_tracestate_dd_propagate_samplingpriority,test_headers_tracestate_dd_propagate_origin,test_headers_tracestate_dd_propagate_propagatedtags
    steps:
      - name: Checkout system tests
        uses: actions/checkout@v3
        with:
          repository: 'DataDog/system-tests'
          # TODO: Delete when https://github.com/DataDog/system-tests/pull/691 lands
          ref: zach/headers-parametric-w3c
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run
        run: |
          cd parametric
          pip install wheel
          pip install -r requirements.txt
          ./run.sh
